# Generated by Django 3.1.1 on 2020-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremierLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Maximum number of 20 characters', verbose_name='Position')),
                ('club', models.CharField(help_text='Maximum text of 30 characters', max_length=30, verbose_name='Club')),
                ('points', models.IntegerField(help_text='Maximum numbers of 3 characters', verbose_name='Points')),
            ],
        ),
    ]
